### ISSUE TITLE
Consider removing all but the six dams that actually visibly contribute by default

### ISSUE THREAD

**Issue by czue** [czue/capetown-drought#7]
Might also help with performance

**Comment by nathanbegbie** [comment]
These are the dams that need removing from the initial visualization:

- Hely-Hutchinson
- Woodhead
- Victoria
- Alexandra
- De Villiers
- KleinPlaats
- Lewis Gay

@czue Unless you have any objections, I'll remove them from the `data.json` file that is generated with python. We can always add this data back in once we've addressed https://github.com/czue/capetown-drought/issues/12 as an option to explore that data.

**Comment by czue** [comment]
sounds good to me!

**Comment by czue** [comment]
I'm going to tackle this one now

**Comment by czue** [comment]
addressed in https://github.com/czue/capetown-drought/pull/15
